import {StyleSheet} from 'react-native';
import Colors from '../../../Constants/Colors';
import {Fonts} from '../../../Constants/Fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingHorizontal: 40,
  },
  disabled: {
    opacity: 0.7,
  },
  horizontalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cancelText: {
    fontFamily: Fonts.boldFontFamily,
    fontSize: 16,
    lineHeight: 18,
    color: Colors.white,
    marginTop: 36,
    alignSelf: 'flex-end',
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: '50%',
    height: 120,
  },
  logo: {
    maxHeight: 120,
    resizeMode: 'contain',
  },
  info: {
    color: '#9D9D9C',
    fontFamily: Fonts.mainFontFamily,
    fontSize: 14,
    lineHeight: 18,
    alignSelf: 'center',
    marginBottom: 18,
    textAlign: 'center',
  },
  inputField: {
    backgroundColor: Colors.white,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Colors.main,
    marginBottom: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,

    fontFamily: Fonts.mainFontFamily,
    color: Colors.gray,
    fontWeight: '300',
    fontSize: 14,
    lineHeight: 18,
  },
  helperText: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '500',
    fontFamily: Fonts.mainFontFamily,
    color: Colors.lightGray,
    marginBottom: 30,
    marginTop: 2,
  },
  registerText: {
    fontSize: 14,
    lineHeight: 18,
    alignSelf: 'center',
    fontFamily: Fonts.mainFontFamily,
    color: Colors.main,
  },
  button: {
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: Colors.main,
    marginBottom: 20,
    width: '60%',
    alignSelf: 'center',
  },
  buttonText: {
    flex: 1,
    fontFamily: Fonts.mediumFontFamily,
    alignSelf: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: 18,
    color: Colors.white,
  },
  // password:
  inputSectionPassword: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 6,
    marginBottom: 20,
    paddingHorizontal: 12,
    paddingVertical: 7,
    maxHeight: 50,
    borderWidth: 1,
    borderColor: Colors.main,
  },
  fieldPassword: {
    flex: 1,
    height: 55,
    fontFamily: Fonts.mainFontFamily,
    color: Colors.gray,
    fontWeight: '300',
    fontSize: 14,
    lineHeight: 18,
  },
  eye: {
    height: 15,
    width: 30,
    resizeMode: 'center',
  },
  touchableEye: {
    marginTop: 7,
    height: 20,
    width: 30,
  },
  checkbox: {
    alignSelf: 'flex-start',
    marginRight: -10,
    marginLeft: 2,
    borderRadius: 1,
  },
  pickServerView: {
    backgroundColor: '#e9e9e9',
    marginTop: 40,
    paddingVertical: 10,
  },
  pickServerText: {
    color: Colors.main,
    fontFamily: Fonts.boldFontFamily,
    alignSelf: 'center',
  },
});
