export default {
  Meteo: {
    Disable: require('../../assets/IconsFromServer/Meteo/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/Meteo/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/Meteo/Error.png'),
    Warning: require('../../assets/IconsFromServer/Meteo/Warning.png'),
    Off: require('../../assets/IconsFromServer/Meteo/Off.png'),
    On: require('../../assets/IconsFromServer/Meteo/On.png'),
  },
  RoadSign: {
    Disable: require('../../assets/IconsFromServer/RoadSign/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/RoadSign/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/RoadSign/Error.png'),
    Warning: require('../../assets/IconsFromServer/RoadSign/Warning.png'),
    Off: require('../../assets/IconsFromServer/RoadSign/Off.png'),
    On: require('../../assets/IconsFromServer/RoadSign/On.png'),
  },
  Qulon: {
    Disable: require('../../assets/IconsFromServer/Qulon/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/Qulon/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/Qulon/Error.png'),
    Warning: require('../../assets/IconsFromServer/Qulon/Warning.png'),
    Off: require('../../assets/IconsFromServer/Qulon/Off.png'),
    On: require('../../assets/IconsFromServer/Qulon/On.png'),
  },
  QulonEnergo: {
    Disable: require('../../assets/IconsFromServer/QulonEnergo/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/QulonEnergo/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/QulonEnergo/Error.png'),
    Warning: require('../../assets/IconsFromServer/QulonEnergo/Warning.png'),
    Off: require('../../assets/IconsFromServer/QulonEnergo/Off.png'),
    On: require('../../assets/IconsFromServer/QulonEnergo/On.png'),
  },
  AHP: {
    Disable: require('../../assets/IconsFromServer/AHP/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/AHP/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/AHP/Error.png'),
    Warning: require('../../assets/IconsFromServer/AHP/Warning.png'),
    Off: require('../../assets/IconsFromServer/AHP/Off.png'),
    On: require('../../assets/IconsFromServer/AHP/On.png'),
  },
  Eco: {
    Disable: require('../../assets/IconsFromServer/Eco/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/Eco/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/Eco/Error.png'),
    Warning: require('../../assets/IconsFromServer/Eco/Warning.png'),
    Off: require('../../assets/IconsFromServer/Eco/Off.png'),
    On: require('../../assets/IconsFromServer/Eco/On.png'),
  },
  Puid: {
    Disable: require('../../assets/IconsFromServer/Puid/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/Puid/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/Puid/Error.png'),
    Warning: require('../../assets/IconsFromServer/Puid/Warning.png'),
    Off: require('../../assets/IconsFromServer/Puid/Off.png'),
    On: require('../../assets/IconsFromServer/Puid/On.png'),
  },
  QulonR: {
    Disable: require('../../assets/IconsFromServer/QulonR/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/QulonR/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/QulonR/Error.png'),
    Warning: require('../../assets/IconsFromServer/QulonR/Warning.png'),
    Off: require('../../assets/IconsFromServer/QulonR/Off.png'),
    On: require('../../assets/IconsFromServer/QulonR/On.png'),
  },
  Luminaire: {
    Disable: require('../../assets/IconsFromServer/Luminaire/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/Luminaire/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/Luminaire/Error.png'),
    Warning: require('../../assets/IconsFromServer/Luminaire/Warning.png'),
    Off: require('../../assets/IconsFromServer/Luminaire/Off.png'),
    On: require('../../assets/IconsFromServer/Luminaire/On.png'),
  },
  LiteWide: {
    Disable: require('../../assets/IconsFromServer/LiteWide/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/LiteWide/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/LiteWide/Error.png'),
    Warning: require('../../assets/IconsFromServer/LiteWide/Warning.png'),
    Off: require('../../assets/IconsFromServer/LiteWide/Off.png'),
    On: require('../../assets/IconsFromServer/LiteWide/On.png'),
  },
  Photo: {
    Disable: require('../../assets/IconsFromServer/Photo/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/Photo/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/Photo/Error.png'),
    Warning: require('../../assets/IconsFromServer/Photo/Warning.png'),
    Off: require('../../assets/IconsFromServer/Photo/Off.png'),
    On: require('../../assets/IconsFromServer/Photo/On.png'),
  },
  Jack: {
    Disable: require('../../assets/IconsFromServer/Jack/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/Jack/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/Jack/Error.png'),
    Warning: require('../../assets/IconsFromServer/Jack/Warning.png'),
    Off: require('../../assets/IconsFromServer/Jack/Off.png'),
    On: require('../../assets/IconsFromServer/Jack/On.png'),
  },
  MeterMerkury230: {
    Disable: require('../../assets/IconsFromServer/MeterMerkury230/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/MeterMerkury230/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/MeterMerkury230/Error.png'),
    Warning: require('../../assets/IconsFromServer/MeterMerkury230/Warning.png'),
    Off: require('../../assets/IconsFromServer/MeterMerkury230/Off.png'),
    On: require('../../assets/IconsFromServer/MeterMerkury230/On.png'),
  },
  MeterPsch4: {
    Disable: require('../../assets/IconsFromServer/MeterPsch4/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/MeterPsch4/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/MeterPsch4/Error.png'),
    Warning: require('../../assets/IconsFromServer/MeterPsch4/Warning.png'),
    Off: require('../../assets/IconsFromServer/MeterPsch4/Off.png'),
    On: require('../../assets/IconsFromServer/MeterPsch4/On.png'),
  },
  MeterQulonRtu: {
    Disable: require('../../assets/IconsFromServer/MeterQulonRtu/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/MeterQulonRtu/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/MeterQulonRtu/Error.png'),
    Warning: require('../../assets/IconsFromServer/MeterQulonRtu/Warning.png'),
    Off: require('../../assets/IconsFromServer/MeterQulonRtu/Off.png'),
    On: require('../../assets/IconsFromServer/MeterQulonRtu/On.png'),
  },
  MeterAvr: {
    Disable: require('../../assets/IconsFromServer/MeterAvr/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/MeterAvr/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/MeterAvr/Error.png'),
    Warning: require('../../assets/IconsFromServer/MeterAvr/Warning.png'),
    Off: require('../../assets/IconsFromServer/MeterAvr/Off.png'),
    On: require('../../assets/IconsFromServer/MeterAvr/On.png'),
  },
  MeterBzp: {
    Disable: require('../../assets/IconsFromServer/MeterBzp/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/MeterBzp/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/MeterBzp/Error.png'),
    Warning: require('../../assets/IconsFromServer/MeterBzp/Warning.png'),
    Off: require('../../assets/IconsFromServer/MeterBzp/Off.png'),
    On: require('../../assets/IconsFromServer/MeterBzp/On.png'),
  },
  MeterMicom: {
    Disable: require('../../assets/IconsFromServer/MeterMicom/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/MeterMicom/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/MeterMicom/Error.png'),
    Warning: require('../../assets/IconsFromServer/MeterMicom/Warning.png'),
    Off: require('../../assets/IconsFromServer/MeterMicom/Off.png'),
    On: require('../../assets/IconsFromServer/MeterMicom/On.png'),
  },
  MeterLightSensor: {
    Disable: require('../../assets/IconsFromServer/MeterLightSensor/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/MeterLightSensor/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/MeterLightSensor/Error.png'),
    Warning: require('../../assets/IconsFromServer/MeterLightSensor/Warning.png'),
    Off: require('../../assets/IconsFromServer/MeterLightSensor/Off.png'),
    On: require('../../assets/IconsFromServer/MeterLightSensor/On.png'),
  },
  Car: {
    Disable: require('../../assets/IconsFromServer/Car/Disable.png'),
    Disconnect: require('../../assets/IconsFromServer/Car/Disconnect.png'),
    Error: require('../../assets/IconsFromServer/Car/Error.png'),
    Warning: require('../../assets/IconsFromServer/Car/Warning.png'),
    Off: require('../../assets/IconsFromServer/Car/Off.png'),
    On: require('../../assets/IconsFromServer/Car/On.png'),
  },
};
